
[Network]
Address = ":19132"

[Players]
Folder = "players"
MaxCount = 0
MaximumChunkRadius = 32
SaveData = true

[Resources]
AutoBuildPack = true
Folder = "resources"
Required = false

[Server]
AuthEnabled = true
JoinMessage = "%v joined CampusWorld"
Name = "CampusWorld Bedrock"
QuitMessage = "%v left CampusWorld"
ShutdownMessage = "CampusWorld Bedrock is restarting."

[World]
Folder = "world"
Name = "CampusWorld"
